/**
 * `clapio generate`: the module a CLI is built from. It carries the OpenAPI document, so the CLI
 * never reads a spec at runtime, and each operation's input (one property per flag) and output as
 * Effect Schemas, so `wrap` is typed against the spec.
 */
import * as Arr from 'effect/Array';
import * as JsonSchema from 'effect/JsonSchema';
import * as Result from 'effect/Result';
import * as SchemaRepresentation from 'effect/SchemaRepresentation';
import { type Command, fromOpenApi } from './manifest.ts';
import type { OpenApiError } from './openapi.ts';

/** What a wrap's `send` takes: a value for any flag, keyed by the flag. */
const inputSchema = ({ parameters }: Command): JsonSchema.JsonSchema => ({
  type: 'object',
  properties: Object.fromEntries(
    parameters.map(({ flag, schema, description }) => [
      flag,
      { ...schema, ...(description === undefined ? {} : { description }) },
    ]),
  ),
  required: parameters.filter(({ isRequired }) => isRequired).map(({ flag }) => flag),
  additionalProperties: false,
});

/** An operation's input and output Effect Schemas, as source, and the imports they need. */
const toCode = (
  command: Command,
  openapi: string,
): { readonly input: string; readonly output: string; readonly imports: ReadonlyArray<string> } => {
  const fromOpenApiSchema = openapi.startsWith('3.0')
    ? JsonSchema.fromSchemaOpenApi3_0
    : JsonSchema.fromSchemaOpenApi3_1;
  const roots = SchemaRepresentation.fromJsonSchemaMultiDocument(
    {
      dialect: 'draft-2020-12',
      schemas: [
        fromOpenApiSchema(inputSchema(command)).schema,
        ...(command.output === undefined ? [] : [fromOpenApiSchema(command.output).schema]),
      ],
      definitions: {},
    },
    { patterns: 'apply' },
  );
  const {
    codes: [input, output],
    references,
    artifacts,
  } = SchemaRepresentation.toCodeDocument(
    SchemaRepresentation.toRepresentations(Arr.map(roots, ({ ast }) => ast)),
  );
  if (input === undefined) throw new Error(`${command.operationId}: its input generated no code`);
  // Schemas reach here inlined and never recursive, so their code stands alone; anything that
  // needs a declaration beside it would be emitted as a dangling name.
  if (
    references.nonRecursives.length > 0 ||
    Object.keys(references.recursives).length > 0 ||
    artifacts.some(({ _tag }) => _tag !== 'Import')
  ) {
    throw new Error(`${command.operationId}: its schemas need declarations clapio doesn't emit`);
  }
  return {
    input: input.runtime,
    // No JSON response: `send` gives back whatever came, usually nothing.
    output: output?.runtime ?? 'Schema.Unknown',
    imports: artifacts.flatMap(artifact =>
      artifact._tag === 'Import' ? [artifact.importDeclaration] : [],
    ),
  };
};

/**
 * The generated module's source for an OpenAPI document, or why a CLI can't be built from it.
 * `source` names the document in the module's header.
 */
export const generate = (
  document: unknown,
  { source }: { readonly source: string },
): Result.Result<string, OpenApiError> =>
  Result.map(fromOpenApi(document), ({ openapi, commands }) => {
    // ponytail: each operation's schemas are inlined, so a shared one repeats per operation;
    // emit `$defs` if a spec's generated module grows too big to read.
    const operations = commands.map(command => ({
      operationId: command.operationId,
      ...toCode(command, openapi),
    }));
    return [
      `// Generated by \`clapio generate\` from ${source}. Don't edit it: generate it again when the spec changes.`,
      "import type * as Clapio from 'clapio';",
      "import * as Schema from 'effect/Schema';",
      ...new Set(operations.flatMap(({ imports }) => imports)),
      '',
      'export const spec = {',
      `  document: ${JSON.stringify(document, null, 2).replaceAll('\n', '\n  ')},`,
      '  operations: {',
      ...operations.map(({ operationId, input, output }) =>
        [
          `    ${JSON.stringify(operationId)}: {`,
          `      input: ${input},`,
          `      output: ${output},`,
          '    },',
        ].join('\n'),
      ),
      '  },',
      '} satisfies Clapio.Spec;',
      '',
    ].join('\n');
  });
