// Generated by `clapio generate` from pets.json. Don't edit it: generate it again when the spec changes.
import type * as Clapio from 'clapio';
import * as Schema from 'effect/Schema';

export const spec = {
  document: {
    "openapi": "3.1.0",
    "info": {
      "title": "Pets",
      "version": "1.0.0"
    },
    "paths": {
      "/stores/{storeId}/pets": {
        "parameters": [
          {
            "name": "storeId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "get": {
          "operationId": "pets.list",
          "summary": "List pets",
          "responses": {
            "200": {
              "description": "The pets",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/Pet"
                    }
                  }
                }
              }
            }
          }
        },
        "post": {
          "operationId": "pets.create",
          "summary": "Add a pet",
          "parameters": [
            {
              "name": "Idempotency-Key",
              "in": "header",
              "schema": {
                "type": "string"
              }
            }
          ],
          "requestBody": {
            "required": true,
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string",
                      "description": "What the pet answers to"
                    },
                    "kind": {
                      "type": "string",
                      "enum": [
                        "cat",
                        "dog"
                      ]
                    },
                    "isIndoor": {
                      "type": "boolean"
                    }
                  },
                  "required": [
                    "name",
                    "kind"
                  ]
                }
              }
            }
          },
          "responses": {
            "201": {
              "description": "The new pet",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/Pet"
                  }
                }
              }
            }
          }
        }
      },
      "/stores/{storeId}/pets/{id}": {
        "parameters": [
          {
            "name": "storeId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "get": {
          "operationId": "pets.get",
          "summary": "Get a pet",
          "responses": {
            "200": {
              "description": "The pet",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/Pet"
                  }
                }
              }
            }
          }
        },
        "delete": {
          "operationId": "pets.delete",
          "responses": {
            "204": {
              "description": "Removed"
            }
          }
        }
      }
    },
    "components": {
      "schemas": {
        "Pet": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "status": {
              "type": "string",
              "enum": [
                "waiting",
                "adopted"
              ]
            }
          },
          "required": [
            "id",
            "name",
            "status"
          ]
        }
      }
    }
  },
  operations: {
    "pets.list": {
      input: Schema.Struct({ "store-id": Schema.String }),
      output: Schema.Array(Schema.StructWithRest(Schema.Struct({ "id": Schema.String, "name": Schema.String, "status": Schema.Literals(["waiting", "adopted"]) }), [Schema.Record(Schema.String, Schema.Json.annotate({ "expected": "JSON value" }))])),
    },
    "pets.create": {
      input: Schema.Struct({ "store-id": Schema.String, "idempotency-key": Schema.optionalKey(Schema.String), "name": Schema.String.annotate({ "description": "What the pet answers to" }), "kind": Schema.Literals(["cat", "dog"]), "is-indoor": Schema.optionalKey(Schema.Boolean) }),
      output: Schema.StructWithRest(Schema.Struct({ "id": Schema.String, "name": Schema.String, "status": Schema.Literals(["waiting", "adopted"]) }), [Schema.Record(Schema.String, Schema.Json.annotate({ "expected": "JSON value" }))]),
    },
    "pets.get": {
      input: Schema.Struct({ "store-id": Schema.String, "id": Schema.String }),
      output: Schema.StructWithRest(Schema.Struct({ "id": Schema.String, "name": Schema.String, "status": Schema.Literals(["waiting", "adopted"]) }), [Schema.Record(Schema.String, Schema.Json.annotate({ "expected": "JSON value" }))]),
    },
    "pets.delete": {
      input: Schema.Struct({ "store-id": Schema.String, "id": Schema.String }),
      output: Schema.Unknown,
    },
  },
} satisfies Clapio.Spec;
